name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build & test
      run: dotnet test -c Release --verbosity normal
      
    - name: Get package version
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: src/OrderCloud.SDK/OrderCloud.SDK.csproj
        
    - name: Get latest release tag
      id: release_version
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ github.token }} #required to see drafts
        exclude_types: prerelease
        view_top: 1
        
    - name: Output versions
      run: |
        echo "package version: ${{ steps.package_version.outputs.version }}"
        echo "latest release: ${{ steps.release_version.outputs.tag_name }}"
      
    - name: Draft release
      env:
        PACKAGE_VER: ${{ steps.package_version.outputs.version }}
        RELEASE_VER: ${{ steps.release_version.outputs.tag_name }}
      if: env.PACKAGE_VER != env.RELEASE_VER
      uses: ncipollo/release-action@v1.10.0
      with:
        tag: ${{ env.PACKAGE_VER }}
        body: "Updates for latest OrderCloud API version"
        artifacts: "ordercloud.sdk.*.nupkg"
        draft: true
