name: Get Version (test)

on: workflow_dispatch

jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get package version
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: src/OrderCloud.SDK/OrderCloud.SDK.csproj

    - name: Get latest release tag
      id: release_version
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft
        
    - name: Release
      env:
        PACKAGE_VER: ${{ steps.package_version.outputs.version }}
        RELEASE_VER: ${{ steps.release_version.outputs.release }}
      if: env.PACKAGE_VER != env.RELEASE_VER
      run: |
        echo "Package version ($PACKAGE_VER) is different than release version ($RELEASE_VER), we should release!"
        
    - name: Don't release
      env:
        PACKAGE_VER: ${{ steps.package_version.outputs.version }}
        RELEASE_VER: ${{ steps.release_version.outputs.release }}
      if: env.PACKAGE_VER == env.RELEASE_VER
      run: |
        echo "Package version ($PACKAGE_VER) and release version ($RELEASE_VER) are the same, no relase needed."
