name: Get Version (test)

on: workflow_dispatch

jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get version
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: src/OrderCloud.SDK/OrderCloud.SDK.csproj

    - name: Echo version
      run: |
        echo "Current version: ${{ steps.package_version.outputs.version }}"
        
    - name: Get latest release
      id: release_version
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft
        
    - name: Echo release
      run: |
        echo "Current release ID: ${{ steps.release_version.outputs.id }}"
        echo "Current release tag: ${{ steps.release_version.outputs.release }}"
