name: Get Version (test)

on: workflow_dispatch

jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get package version
      id: package_ver
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: src/OrderCloud.SDK/OrderCloud.SDK.csproj

    - name: Get latest release 1
      id: release_1
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: ${{ github.repository }}
        excludes: prerelease
        
    - name: Get latest release 2
      id: release_2
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        exclude_types: prerelease
        
    - name: Echo
      run: |
        echo "package version: ${{ steps.package_ver.outputs.version }}"
        echo "release_1.id: ${{ steps.release_1.outputs.release }}"
        echo "release_1.release: ${{ steps.release_1.outputs.release }}"
        echo "release_2.id: ${{ steps.release_2.outputs.id }}"
        echo "release_2.name: ${{ steps.release_2.outputs.name }}"
        echo "release_2.tag_name: ${{ steps.release_2.outputs.tag_name }}"
        echo "release_2.draft: ${{ steps.release_2.outputs.draft }}"
        
