name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-to-nuget:
    runs-on: ubuntu-latest

    steps:
      - name: Download package
        uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          filename: "*.nupkg"
          token: ${{ github.token }}
